### PR TITLE
accept the param month as a number between 1 and 12

### PR DESCRIPTION
**Pull request by coderhaoxin**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
@ramalho JS date api's `month` is not user-friendly :cry:

**Comment by coderhaoxin** [comment]
@ramalho any feedback on this?

**Comment by liuyuehe92** [comment]
+1

**Comment by ramalho** [comment]
@coderhaoxin your suggestion is an improvement, however, I chose 0 to stand for January to be consistent with the (silly) JavaScript Date object (see: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date).

I will reject your pull request because changing this now will break other people's code that depends on current behavior. Please create a fork with a different name, such as calendar1.js, OK? Good luck!

**Pull request closed without merging**
